### ISSUE TITLE
It would be good to support .yaml file extension

### ISSUE THREAD

**Issue by StephenNay** [javanile/yamlinc#1]
This is a nice little tool, but I initially had trouble with it because all of my YAML files use .yaml instead of .yml as the file extension. When I tried to use yamlinc with one of those files, all I got was

Arguments error >> missing file name.

After trying a few other things, I eventually guessed that yamlinc might only recognize .yml file extensions, which turned out to be correct. 

If you get a chance, please modify yamlinc to recognize .yaml file extensions as valid.

**Comment by francescobianco** [comment]
@StephenNay Good news! Support for multiple file extension is now on v0.0.63.
try to update with

`$ npm install -g yamlinc`

**Comment by Zaijo** [comment]
Isn't this already solved? npm has v0.1.1 already.

**Comment by francescobianco** [comment]
@StephenNay @Zaijo Yes! It works!
