### ISSUE TITLE
Support path glob

### ISSUE THREAD

**Issue by boesing** [javanile/yamlinc#4]
Hey there,

would be nice if the `$include` could handle a glob value.
Maybe like `.gitignore`, where you can set something like:

```
**/*.yaml
**/foo.yaml
```

Which would checkout the following example paths:

```
src/foo/bar/baz.yaml
src/foo/bar.yaml
src/foo.yaml
```

**Comment by arvind-agarwal** [comment]
@francescobianco thanks for the good work. Is this feature implemented in 0.2.0 branch?

**Comment by francescobianco** [comment]
@boesing @arvind-agarwal 
version 0.2.0 supports the Glob but is still under development could go online in March. 
Thank you for your patience.

**Comment by JasonHenriksen** [comment]
This would be super handy.  I'm willing to contribute some time if it would help...

**Comment by francescobianco** [comment]
@JasonHenriksen Yes, of course, it would be appreciated.
This branch is starting point for the next version
https://github.com/javanile/yamlinc/tree/0.2.0-dev

**Comment by boesing** [comment]
As we already found a workaround, I'll close this one.
Thanks for your efforts.
